name: Deploy to Railway

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    name: Deploy with Wasp
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wasp
        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s -- -v 0.16.0 # Change to your Wasp version

      - name: Wasp Build
        run: wasp build

      - name: Change directory
        run: cd .wasp/build

      - name: install railway
        run: npm install -g @railway/cli

      - run: railway up --service=${{ env.SVC_ID }}